# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6d4fc5690d109d59fcdaf0bb3dec5724cfb6d3432e9b37b950e9ab5ed9c91d355eab316d9960dcf8999ef00be8107ed7197dacd2aed5ced70b7fdde20a2c82d

test:
  secret_key_base: 64f0ec50bce7e613350ca48a40bab90795443ed50b888e293fef69f120be64d76d8b0ed8d5631f36721bc3b2d6705783eb26a9bd5d622f40495443840c548b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
